version: '3'

services:
  web:
    image: presstheredbutton/myapp_web:prod
    ports:
      - "3000:3000"
      - "4000:3000"
    env_file:
      - .env/production/database
      - .env/production/web
    deploy:
      replicas: 2

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  db-migrator:
    image: presstheredbutton/myapp_web:prod
    command: ["./wait-for", "--timeout=300", "database:5432", "--",
              "bin/rails", "db:migrate"]
    env_file:
      - .env/production/database
      - .env/production/web
    deploy:
      restart_policy:
        condition: none

volumes:
  db_data:
